config/routes.rb
Rails.application.routes.draw do

root 'static_pages#index'

get 'games', to: 'static_pages#games'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VPcalc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar justify-content-between"><%= link_to 'VPCALC', root_path, class: 'navbar-brand' %>
      <div>
        <button class="btn lgn-btn my-2 my-sm-0" type="log-in">Login</button>
      </div>
    </nav>
    <div class="pages">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col">
            <h3>Footer Nonsense</h3>
            <p>more stuff later</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/static_pages/games.html.erb
<div class="games-page">
  <select id="drprojecttype" name="drprojecttype" class="form-control drop-down">
    <option value="0">--Select Game--</option>
    <option value="Adhoc">Game1</option>
    <option value="Dedicated">Game2</option>
    <option value="other">Game3</option>
  </select>
  <div class="hand-box">
    <div class="row">
      <div class="card-box">
      </div>
      <div class="card-box">
      </div>
      <div class="card-box">
      </div>
      <div class="card-box">
      </div>
      <div class="card-box">
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="btn calculate-btn col-md-4 m-*-auto">
      Calculate
    </div>
  </div>
</div>



<script>
  if (projecttype == "FTE" || projecttype == "Retainer") {
    $("#drprojecttype option[value='Dedicated']").attr("selected", "selected");
  }
  else {
      // $("#drprojecttype").val("Adhoc");
      $('select[name^="drprojecttype"] option:selected').attr("selected", null);
      $("#drprojecttype option[value='Adhoc']").attr("selected", "selected");
  }
</script>

app/views/static_pages/index.html.erb
<div class="landing">
  <br />
  <div class="welcome-box col-8 offset-2 hidden-xs-down text-center">
    <h1>Welcome to VPCalc</h1>
    <p>
      Stupid place holder stuff... Were not even sure if were going to call it VPCALC of VPCalc!
    </p>
  </div>
</div>

<div class="row info-pane">
  <div class="col-md-3 offset-1 col-10 info-box">
    <h2 class="full-link"><%= link_to 'Select Game', games_path %><h2>
    
  </div>
  <div class="col-md-3 offset-1 col-10 info-box">
    <h2>Learn More</h2>
  </div>
  <div class="col-md-3 offset-1 col-10 info-box">
    <h2>Find Machines</h2>
  </div>
</div>